services:
  traefik:
    image: traefik:latest
    container_name: traefik
    restart: unless-stopped
    command:
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      - --providers.docker.network=traefik_proxy
      - --entrypoints.web.address=:80
      - --api.dashboard=true
      - --api.insecure=true
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - traefik_proxy

  gluetun:
    image: qmcgaw/gluetun:v3
    container_name: gluetun
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    expose:
      - "9091"
      - "51413"
      - "8000"
    environment:
      - VPN_SERVICE_PROVIDER=protonvpn
      # - VPN_TYPE=${VPN_TYPE:-openvpn}
      # - SERVER_COUNTRIES=${SERVER_COUNTRIES:-Mexico,United States,Singapore,Japan,Canada,Norway,Poland,Romania,Switzerland}
      - TZ=${TZ:-UTC}
      - FIREWALL_INPUT_PORTS=9091,51413,8000
      - HTTP_CONTROL_SERVER_ADDRESS=:8000
      - 'HTTP_CONTROL_SERVER_AUTH_DEFAULT_ROLE={"auth":"none"}'
      - FREE_ONLY=true
      - UPDATER_PERIOD=24h
    env_file:
      - ../.env
    restart: unless-stopped
    networks:
      - traefik_proxy

networks:
  traefik_proxy:
    name: traefik_proxy
    driver: bridge
