http:
  routers:
    gluetun-webui-slash:
      rule: (Host(`localhost`) || Host(`bugaboxes.local`)) && Path(`/gluetun-webui`)
      entryPoints:
        - web
      priority: 120
      middlewares:
        - gluetun-webui-add-slash
      service: noop@internal

    gluetun-webui:
      rule: (Host(`localhost`) || Host(`bugaboxes.local`)) && PathPrefix(`/gluetun-webui/`)
      entryPoints:
        - web
      priority: 110
      middlewares:
        - gluetun-webui-strip
      service: gluetun-webui

    gluetun-webui-api:
      rule: (Host(`localhost`) || Host(`bugaboxes.local`)) && PathPrefix(`/api`)
      entryPoints:
        - web
      priority: 115
      service: gluetun-webui

  middlewares:
    gluetun-webui-add-slash:
      redirectRegex:
        regex: ^https?://([^/]+)/gluetun-webui$
        replacement: http://$1/gluetun-webui/
        permanent: true

    gluetun-webui-strip:
      stripPrefix:
        prefixes:
          - /gluetun-webui

  services:
    gluetun-webui:
      loadBalancer:
        servers:
          - url: http://gluetun-webui:3000
